server:
  port: 9090

logging:
  level:
    root: WARN
    org.springframework.security: INFO
    com.yejy.app.data.BlogMapper : TRACE

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://www.yejinyun.cn:3306/serp
    username: yejy
    password: kfJINdifc186@*

mybatis:
  type-aliases-package: com.yejy.app.model
  configuration:
    cache-enabled: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  mapper-locations: classpath:mybatis/mapper/*.xml

token:
  key: '@ay*L(M_~M245!'
  issuer: http://www.yejinyun.cn/
  subject: LoveSystem@yejy.cn
  expiration: 3600000
  header: user_token

