spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url:
    username:
    password:
mybatis:
  type-aliases-package: com.yejy.app.model
  configuration:
    cache-enabled: true
  mapper-locations: classpath:mybatis/mapper/*.xml
