server:
  port: 9090

logging:
  level:
    root: WARN
    org.springframework.security: INFO
    com.yejy.app.data.BlogMapper : TRACE

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://www.yejinyun.cn:3306/serp?useUnicode=true&characterEncoding=utf8
    username: yejy
    password: kfJINdifc186@*
  http:
    encoding:
      enabled: true
      charset: UTF-8
      force-response: true
      force: true

mybatis:
  type-aliases-package: com.yejy.app.model
  configuration:
    cache-enabled: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  mapper-locations: classpath:mybatis/mapper/*.xml

token:
  key: '@ay*L(M_~M245!'
  issuer: http://www.yejinyun.cn/
  subject: LoveSystem@yejy.cn
  expiration: 3600000
  header: user_token

alipay:
  server_url: https://openapi.alipay.com/gateway.do
  app_id: 2018032802459274
  app_private_key: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCcP4osVm4vnAWSJtMpNPULlC+6nvozyErwOK5QM1kjLTrB/tY19J0bi57Rw/HyH7FImQGk9zE2nyDf6/0vmF/8mg3Hb8ePvo5KuRKq7fKLnDvg4jsR9vaeIUvRJHnMQPrHBQdAfRGQ9GZH0HHgq0iGYKbOzrbiI+WPMIctviB0i8L8ZZV2Z8rc3Q6T+o5BneYKJE4Lh5oH5p/0UbPi14JS7Ed6b3KzVtubds/FvbYmLRt+aizUPfX3WvBuZDJ0Tg2zSLZiMLm5Pe6Yjk/3Kmun54m6+gHIl7VeXdzdbHguHKUZxLw6D/y8Q5fUiQmN0gvELYYuWQjZZk17I64zlJPjAgMBAAECggEAUfTiPS94zHBCW88Ro+OrRU+NWY5aHx9Ib4jLpjXI47Ktx2QsaFDOt8wcmlr1ZdNJ4pKfUjB3F/eP/uSCAZ0jfBQydhIj0zpY2MkLCa2WM7TXk7YW1e18nqVIZ4OCf6j14b65dxIjTK1lmPW1ReuSNyorVP8I3sWFe/4wacX4sChtV/0mHS2A8kORZu0vkTkaVFCjt6cdABR5ITnbWQm/IUvdS7Fe/F/nDrM/QQxHZyeXbTnBCKCeerJGvT6bHLJtzh4CVqs331VP1Y5RzRRSO55vk310aFceV8bC6hfvggCy12BkXIQvZsP4caTI4dgyENQLPlVylVKxso1CWybLQQKBgQDMrNZu965filTy+ZlxClfr4ctb9NIMIoVx2+NZB9aWMhdJPbVB4bysGUKrAkU70xRXSHJqEoNlXwv+xUlgo80fAazIEnrw7NHfGDvMf4uPDVyM1k8IXgse0iU2V3FjPc7Y1Brg4gpGISU4/j6Z2AEnvbwUGeu9yrS4d6DYa7WbDQKBgQDDbeyzE/71e14UQa43nsCtnwBqMVGcJAsGBIKi6+KoAnw8FLOtSm59kGzgKLlprVzQNZoAGk5/8syjvPanblcIEbyxznKIjl1Ksuqd9Bb5FOhwhEuX2K4FMH7AfgkwghX/kR9u0Y3gOldkGPo6R8UvQzmm2MknOzeyKseb/RBurwKBgBWYiwusYJ6+FtaIVZNi1wIRkgaC34LeRZxM6kEjnZW9dU2KEE0CR4kVJT6r/6gfTn8jKsdcarbQf5CDOonS3rrNz3BQ2t3+7uoOQYkDUDNo4oINvssQOTYoUDraoSEqjV+9iZR+5TyfFLFdyjcrXnvV/jlUvtYIxGbOYI9VVhUlAoGAcmNtIISbv2QudPzc1IF/liBzRbUIZ7RRH3yUWnhnep+5yBD1+oCOm8Blee9cV5a5tMUrFtRPDmU3kr+QQAA9wONg51JHh9aMlKSU3094AuNSCknlVUPm1/LCvjkHd/UsmyJ+m4bc3FpJvLVCAcrwh/F5VUeete/bcdXIcG13qNECgYAbDcuQtI5b5CSYg5iKJIwZrytTBBoGOtlfQuHk7Xr93iS3GwiaFMRSAPxAWh3vs1MFBIgn1mIwDo0qtaR4HHj8G1enc4zHRet9/euRLAMTeaRW3SeVsveT1+UN8Y6WkoFC9Ehci9IKZRpWiFRvZjaCSb03xLvakN+W+OTnq5fEVw==
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnD+KLFZuL5wFkibTKTT1C5Qvup76M8hK8DiuUDNZIy06wf7WNfSdG4ue0cPx8h+xSJkBpPcxNp8g3+v9L5hf/JoNx2/Hj76OSrkSqu3yi5w74OI7Efb2niFL0SR5zED6xwUHQH0RkPRmR9Bx4KtIhmCmzs624iPljzCHLb4gdIvC/GWVdmfK3N0Ok/qOQZ3mCiROC4eaB+af9FGz4teCUuxHem9ys1bbm3bPxb22Ji0bfmos1D3191rwbmQydE4Ns0i2YjC5uT3umI5P9yprp+eJuvoByJe1Xl3c3Wx4LhylGcS8Og/8vEOX1IkJjdILxC2GLlkI2WZNeyOuM5ST4wIDAQAB
  format: json
  charset: utf-8
  signType: RSA2

